### ISSUE TITLE
No module named 'watchdog' error weh

### ISSUE THREAD

**Issue by charlespick** [ansible/ansible-rulebook#609]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/ansible-rulebook/issues) for duplicates.
- [X] I understand that ansible-rulebook is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When following the instructions at main/docs/installation.rst, on a fresh installation of Ubuntu Server you get a traceback ending with no module named watchdog found. I followed the instructions to a tee and also got the same result on Fedora server although I am not as familiar with Fedora so that may be my fault who knows. 
I searched for other issues with the keyword "watchdog" and found nothing but I apologize if this is a duplicate. 

### Environment

Ubuntu 22.04.3 LTS Server
openjdk 17 installed with apt
python 3.10.12 preinstalled
pip3 installed with apt

### Steps to reproduce

Install Ubuntu
```
apt-get --assume-yes install openjdk-17-jdk python3-pip
export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
export PATH=$PATH:~/.local/bin
pip3 install ansible ansible-rulebook ansible-runner
```
from the docs
`ansible-rulebook`

### Actual results

```
Traceback (most recent call last):
  File "/home/charlespick/.local/bin/ansible-rulebook", line 5, in <module>
    from ansible_rulebook.cli import main
  File "/home/charlespick/.local/lib/python3.10/site-packages/ansible_rulebook/cli.py", line 35, in <module>
    from ansible_rulebook import app  # noqa: E402
  File "/home/charlespick/.local/lib/python3.10/site-packages/ansible_rulebook/app.py", line 32, in <module>
    from ansible_rulebook.engine import run_rulesets, start_source
  File "/home/charlespick/.local/lib/python3.10/site-packages/ansible_rulebook/engine.py", line 25, in <module>
    from watchdog.events import FileSystemEventHandler
ModuleNotFoundError: No module named 'watchdog'
```

### Expected results

Help message or results when run with parameters and rulebook

**Comment by charlespick** [comment]
I fixed this by injecting Watchdog manually. Is there a reason Watchdog isn't a dependency?

**Comment by ttuffin** [comment]
Hi @charlespick, if you have already installed the [event-driven-ansible](https://github.com/ansible/event-driven-ansible) collection and still see this error then it's because the Python dependencies have not been installed. The `watchdog` library is a dependency for the ansible.eda collection and since ansible-galaxy doesn't handle the installation of Python dependencies they will need to be installed manually. We do include `watchdog` in the collection's [requirements.txt](https://github.com/ansible/event-driven-ansible/blob/main/requirements.txt) and it is one of the steps included in the [Install section](https://github.com/ansible/event-driven-ansible#install) for the collection.

Hope that helps.

**Comment by Alex-Izquierdo** [comment]
Hi @charlespick @ttuffin This seems a bug introduced in https://github.com/ansible/ansible-rulebook/pull/516
As our CI pipelines already install the collection which contains that dependency we have not detected the missing dependency. It is just a matter to add the dependency in the ansible-rulebook requirements. 

Thanks for the report.

**Comment by Alex-Izquierdo** [comment]
I expect to release 1.0.4 with this fix today or tomorrow as latest
